- igniteui-webcomponents.ts
- src/components/badge/badge.material.scss
- src/components/badge/badge.ts
- stories/badge.stories.ts
- test/badge.test.ts
> feat(badge): add initial implementation

- igniteui-webcomponents.ts
- src/components/ripple/ripple.scss
- src/components/ripple/ripple.ts
- stories/ripple.stories.ts
Closes #20 
[Specification](https://github.com/IgniteUI/igniteui-webcomponents/wiki/Ripple-Specification)
> feat(ripple): Added implementation

- src/components/input/input.bootstrap.scss
- src/components/input/input.material.scss
> fix(input): bump input z-index

- gulpfile.js
- package-lock.json
- package.json
- tsconfig.json
> docs(*): Adding typedoc

- src/components/common/decorators/blazorInclude.ts
- src/components/common/decorators/index.ts
- src/components/icon/icon.ts
add convenience methods for icon registry for blazor.
> add icon api for blazor

- src/components/common/mixins/sizable.ts
- src/index.ts
> chore(*): Export base classes and mixins.

- src/components/calendar/calendar.ts
- src/components/calendar/common/calendar-base.ts
- src/components/calendar/months-view/months-view.ts
- src/components/calendar/years-view/years-view.ts
> fix(calendar): remove circular dependency

- src/components/calendar/calendar.fluent.scss
> refactor(themes): remove deprecation warnings

- README.md
> Update Usage section in readme

- scripts/_package.json
> fix(package): fix sideEffects paths

- src/components/nav-drawer/nav-drawer-item.ts
> chore(*): fix eslint warning

- src/components/button/button.fluent.scss
- src/styles/themes/fluent.scss
> refactor(button): improve fluent button styles

- src/components/checkbox/checkbox.fluent.scss
> refactor(checkbox): update focus state

- src/components/checkbox/switch.dark.fluent.scss
- src/components/checkbox/switch.dark.indigo.scss
- src/components/checkbox/switch.fluent.scss
- src/styles/themes/dark/fluent.scss
- src/styles/themes/dark/indigo.scss
> feat(switch): implement dark themes

- src/styles/common/component.scss
- src/styles/themes/base/_bootstrap.scss
- src/styles/themes/base/_fluent.scss
- src/styles/themes/base/_indigo.scss
- src/styles/themes/base/_material.scss
- src/styles/utilities/_mixins.scss
- stories/nav-drawer.stories.ts
> Add scrollbars styles based on the selected theme

- CHANGELOG.md
- src/components/calendar/calendar-rendering.spec.ts
- src/components/calendar/calendar.ts
- src/components/card/card.bootstrap.scss
- src/components/card/card.fluent.scss
- src/components/card/card.material.scss
- src/components/card/card.spec.ts
- src/components/card/card.ts
- stories/calendar.stories.ts
- stories/card.stories.ts
> Changed boolean properties to default to false.

- CHANGELOG.md
- src/components/calendar/calendar.interaction.spec.ts
- src/components/calendar/calendar.ts
- src/components/calendar/common/calendar-base.ts
- src/components/calendar/days-view/days-view.ts
- stories/calendar.stories.ts
> refactor(calendar): split value into two props

- src/components/slider/slider-base.ts
- src/components/slider/slider.material.scss
- stories/calendar.stories.ts
The slider track was not appearing in the samples repo. In order to fix it I have removed the z-index an made sure the elements are in the correct order in the DOM.
> fix(slider): remove z-index

- CHANGELOG.md
- src/components/nav-drawer/nav-drawer.spec.ts
- src/components/nav-drawer/nav-drawer.ts
- stories/nav-drawer.stories.ts
> fix(nav-drawer): remove events

- src/components/slider/slider.bootstrap.scss
> fix(slider): bootstrap height

- scripts/build-stories.js
- src/components/common/definitions/defineAllComponents.ts
- src/components/slider/range-slider.ts
- src/components/slider/slider-base.ts
- src/components/slider/slider-label.ts
- src/components/slider/slider.material.scss
- src/components/slider/slider.spec.ts
- src/components/slider/slider.ts
- src/index.ts
- stories/range-slider.stories.ts
- stories/slider.stories.ts
> feat(slider): replace labelFormatter

- src/components/input/input.spec.ts
- src/components/input/input.ts
> fix(input): Wait for update before validating

- src/components/checkbox/themes/light/switch.bootstrap.scss
> refactor(switch): update component to match latest boostrap spec

- src/components/input/input-base.ts
- src/components/input/input.ts
- src/index.ts
- stories/input.stories.ts
> feat(input): add base input component

- src/components/avatar/avatar.bootstrap.scss
> Change avatar border radius in bootstrap theme

- CHANGELOG.md
> Update changelog with newly added components

- src/components/button/themes/icon-button/light/icon-button.fluent.scss
closes #270
Related to [#11129](https://github.com/IgniteUI/igniteui-angular/issues/11129) and [#11120](https://github.com/IgniteUI/igniteui-angular/issues/11120)
> Update the fluent/flat icon-button to match ms-fluent and angular/fluent

- src/components/chip/chip.ts
- src/components/dropdown/dropdown.ts
- src/components/input/input-base.ts
- src/components/toggle/utilities.ts
some urgency is needed on this one to unbreak the blazor build.
> blazor new components fixes

- CHANGELOG.md
- src/components/calendar/calendar-rendering.spec.ts
- src/components/calendar/common/calendar-base.ts
> feat(calendar): Set active date through attribute

- src/components/button/themes/button/light/button.bootstrap.scss
- src/components/button/themes/button/light/button.indigo.scss
Related to:
IgniteUI/igniteui-angular/issues/11233 
IgniteUI/igniteui-angular/issues/11231
> fix(button): height discrepancy

- src/components/button/themes/icon-button/light/icon-button.base.scss
- src/components/button/themes/icon-button/light/icon-button.bootstrap.scss
- src/components/button/themes/icon-button/light/icon-button.fluent.scss
- src/components/button/themes/icon-button/light/icon-button.indigo.scss
Related to:
IgniteUI/igniteui-angular/issues/11285
IgniteUI/igniteui-angular/issues/11231
IgniteUI/igniteui-angular/issues/11232
IgniteUI/igniteui-angular/issues/11233
> fix(button): icon button size discrepancy

- CHANGELOG.md
- src/components/common/definitions/defineAllComponents.ts
- src/components/dropdown/dropdown-group.ts
- src/components/dropdown/dropdown-header.ts
- src/components/dropdown/dropdown-item.ts
- src/components/dropdown/dropdown.spec.ts
- src/components/dropdown/dropdown.ts
- src/index.ts
- stories/dropdown.stories.ts
> refactor: Renamed dropdown types/classes

- src/components/chip/chip.ts
- src/components/icon/icon.registry.ts
- stories/chip.stories.ts
> fix(chip): Load internal icons

- src/components/chip/themes/chip.base.scss
> fix(chip): selected chip is misaligned

- src/components/calendar/calendar-rendering.spec.ts
> fix failing calendar-rendering test

- src/components/nav-drawer/styles/indigo/nav-drawer-item.indigo.scss
- src/components/nav-drawer/styles/nav-drawer-item.base.scss
> fix(nav-drawer): remove redundant margin

- src/components/button/themes/button/light/button.base.scss
- src/components/button/themes/icon-button/light/icon-button.base.scss
> style(button/icon-button): add vertical align to button and icon-button

- src/components/checkbox/themes/light/switch.base.scss
> fix(switch): fix switch getting shrinked when space is small

- src/components/nav-drawer/styles/nav-drawer.base.scss
> feat(navdrawer): add border on relative navdrawer

- src/styles/themes/base/_bootstrap.scss
- src/styles/themes/base/_fluent.scss
> fix(typography): differences between Ignite UI for Angular and WC

- src/components/navbar/navbar.ts
- src/components/navbar/themes/light/navbar.base.scss
- src/components/navbar/themes/light/navbar.bootstrap.scss
- src/components/navbar/themes/light/navbar.fluent.scss
> fix(navbar): typography discrepancy

- src/components/button/button-base.ts
> fix(buttons): set delegatesFocus on buttons

- src/components/mask-input/mask-input.spec.ts
- src/components/mask-input/mask-input.ts
> fix(masked): Drop text behavior

- src/components/list/themes/light/list.base.scss
- stories/list.stories.ts
> fix(list): allow the list to scroll

- src/components/input/input-base.ts
> fix(input): remove helper text container when empty

- src/components/icon/icon.material.scss
> fix(icon): fix icon not showing in safari

- src/components/checkbox/themes/light/checkbox.base.scss
> fix(checkbox): fix check not showing in safari

- src/components/date-time-input/date-time-input.spec.ts
- src/components/date-time-input/date-time-input.ts
- stories/date-time-input.stories.ts
> Date Time Input - emit igcInput/igcChange correctly

- CHANGELOG.md
- src/components/dropdown/dropdown.spec.ts
- src/components/toggle/toggle.controller.ts
> fix(dropdown): Dispose of top-level event listeners

- src/components/progress/linear-progress.spec.ts
- src/components/progress/linear-progress.ts
- src/components/progress/themes/linear/linear.progress.base.scss
- src/components/progress/themes/linear/linear.progress.bootstrap.scss
- src/components/progress/themes/linear/linear.progress.fluent.scss
- src/components/progress/themes/linear/linear.progress.indigo.scss
- src/components/progress/themes/shared.scss
> fix linear progress animations

- src/components/accordion/accordion.ts
- src/components/button/button-base.ts
- src/components/calendar/common/calendar-base.ts
- src/components/checkbox/checkbox-base.ts
- src/components/common/decorators/blazorDeepImport.ts
- src/components/input/input-base.ts
- src/components/mask-input/mask-input-base.ts
- src/components/slider/slider-base.ts
annotations necessary to correct the blazor build
> blazor annotations

- README.md
> chore(*): readme-update-3.3.0

- src/components/rating/rating.spec.ts
- src/components/rating/rating.ts
- stories/rating.stories.ts
> fix(rating): Improved a11y

- src/components/button/themes/button/light/button.base.scss
> fix(button): misaligned icon prefix / suffix

- src/components/slider/range-slider.ts
- src/components/slider/slider-base.ts
> fix(range-slider): add ariaValueText

- src/components/calendar/themes/days-view.base.scss
> refactor(calendar): update weekend days color

- src/components/button/icon-button.spec.ts
- src/components/button/icon-button.ts
- src/components/button/themes/icon-button/light/icon-button.base.scss
- stories/icon-button.stories.ts
> fix(icon-button): icon not showing when using ripple

- src/components/progress/themes/circular/circular.progress.base.scss
- src/components/progress/themes/circular/circular.progress.bootstrap.scss
- src/components/progress/themes/circular/circular.progress.fluent.scss
- src/components/progress/themes/shared.scss
- src/components/progress/themes/vars.scss
> style(circular-progressbar): fix safari bugs

- src/components/radio/radio.ts
> refactor(radio): reportValidity doesn't return value

- src/components/select/themes/light/select.base.scss
> fix(select): prefix misalignment

- src/components/select/select.ts
> refactor(select): focus target on change event

- src/components/checkbox/checkbox-base.ts
- src/components/input/input.ts
- src/components/radio/radio.ts
- src/components/select/select.ts
> refactor(*): add checkValidity to input-like form elements

- src/components/dialog/themes/light/dialog.base.scss
> fix(dialog): remove content max-width

- ROADMAP.md
Update of the ROADMAP after 22.2 release
> chore(*): roadmap-update-15-nov-2022

- src/components/input/themes/light/input.base.scss
- src/components/input/themes/light/input.material.scss
> feat(input) add label ellipsis

- src/components/select/select.spec.ts
- src/components/select/select.ts
> fix(select): make checkValidity to only return whether the component is valid

- src/components/combo/themes/light/combo.base.scss
- src/components/input/themes/light/input.base.scss
- src/components/input/themes/light/input.bootstrap.scss
- src/components/input/themes/light/input.fluent.scss
- src/components/input/themes/light/input.indigo.scss
- src/components/input/themes/light/input.material.scss
- src/components/select/themes/light/select.base.scss
- stories/input.stories.ts
- stories/select.stories.ts
> fix(inputs): helper text should be error 500 color when invalid

- package-lock.json
- package.json
- scripts/_package.json
- src/components/combo/combo-list.ts
- src/components/combo/combo.spec.ts
- src/components/combo/combo.ts
- src/components/combo/controllers/navigation.ts
Update the scrolling logic to work with the latest version of lit-virtualizer.
> refactor(combo): switch to latest version of virtualizer

- src/components/card/themes/light/card.content.bootstrap.scss
- src/components/card/themes/light/card.content.indigo.scss
- src/components/card/themes/light/card.content.material.scss
- src/components/card/themes/light/card.header.bootstrap.scss
- src/components/card/themes/light/card.header.indigo.scss
- src/components/card/themes/light/card.header.material.scss
> fix(card): color discrepancy between WC and Angular

- src/components/input/input-base.ts
> fix(input): Do not cache the underlying input

- src/components/nav-drawer/themes/light/fluent/nav-drawer-item.fluent.scss
- src/components/nav-drawer/themes/light/indigo/nav-drawer-item.indigo.scss
- src/components/nav-drawer/themes/light/nav-drawer-item.base.scss
- src/components/slider/slider.spec.ts
> fix(nav-drawer): remove !important from item styles

- src/components/combo/themes/light/combo.indigo.scss
- src/components/combo/themes/light/combo.material.scss
- src/components/input/themes/light/input.indigo.scss
- src/components/input/themes/light/input.material.scss
- src/components/select/themes/light/select.indigo.scss
- src/components/select/themes/light/select.material.scss
> refactor(input): sizable padding for helper text and input

- src/components/combo/combo.ts
- stories/combo.stories.ts
> fix(combo): matched item not active in single selection mode

- src/components/dialog/themes/light/dialog.fluent.scss
> fix(dialog): update fluent backdrop color

- src/components/combo/combo.spec.ts
- src/components/combo/combo.ts
- src/components/combo/controllers/data.ts
- src/components/combo/controllers/selection.ts
- src/components/combo/types.ts
> fix(combo): selection API doesn't work with filtered data

- src/components/calendar/calendar.ts
- src/components/calendar/themes/calendar.base.scss
- src/components/calendar/themes/fluent/calendar.fluent.scss
- src/components/calendar/themes/fluent/dark/index.scss
- src/components/calendar/themes/fluent/days-view.fluent.scss
- src/components/calendar/themes/fluent/vars.scss
- src/components/calendar/themes/fluent/year-month-view.fluent.scss
- src/components/icon/icon.registry.ts
- src/styles/themes/dark/fluent.scss
> refactor(calendar): update fluent design to match UI kit

- src/components/input/themes/light/input.material.scss
- stories/input.stories.ts
- stories/story.ts
> fix(input): update stories and styles for size attribute

- src/components/date-time-input/date-util.spec.ts
See https://github.com/nodejs/node/issues/45938
> chore: Fixed Intl unit test & updated dependencies

- src/components/calendar/themes/fluent/days-view.fluent.scss
> fix(theme): fluent theme calendar range

- src/components/avatar/themes/avatar.base.scss
- src/components/badge/themes/light/badge.base.scss
- src/components/button/themes/button/light/button.base.scss
- src/components/button/themes/icon-button/light/icon-button.base.scss
> fix host sizes for avatar, badge, button, icon-button.

- src/components/toast/themes/toast.base.scss
- src/components/toast/themes/toast.fluent.scss
> fix(toast): update fluent typography

- src/components/input/themes/light/input.bootstrap.scss
> fix(input): visual issues on iOS

- src/components/button/themes/button/light/button.base.scss
- src/components/button/themes/button/light/button.bootstrap.scss
- src/components/button/themes/button/light/button.fluent.scss
- src/components/button/themes/button/light/button.indigo.scss
- src/components/button/themes/button/light/button.material.scss
> refactor(button) background to be on an element on which can easily be changed.

- src/components/button/themes/button/light/button.base.scss
> style(button) Override material-icons font-size.

- src/components/common/definitions/defineAllComponents.ts
> add missing components

- src/components/radio/themes/dark/radio.fluent.scss
- src/components/radio/themes/light/radio.fluent.scss
> fix(radio): fluent theme inconsistencies

- src/components/button/icon-button.ts
- src/components/button/themes/icon-button/light/icon-button.base.scss
> fix(icon-button): set icon size to always be 1.125rem/18px

- src/components/chip/themes/chip.fluent.scss
- src/components/chip/themes/chip.material.scss
Related IgniteUI/igniteui-angular#12771
> Chip - Remove outline styls for material and fluent themes.

- src/components/tabs/themes/light/tab-panel.base.scss
- src/components/tabs/themes/light/tab.base.scss
- src/components/tabs/themes/light/tabs.base.scss
> fix(tabs): make tabs and tab panels to take the full width of their parent

- src/components/navbar/themes/light/navbar.base.scss
- stories/navbar.stories.ts
> fix(navbar): content doesn't overflow

- src/components/tabs/tabs.ts
> Fix nested tabs selection

- src/components/dialog/dialog.ts
Mostly for static analysis that currently will miss the blazor suppress if on the getter
> refactor(dialog): reorder closeOnEscape setter/getter

- src/components/dialog/themes/light/dialog.base.scss
> fix(dialog): backdrop doesn't overlay elements

- src/components/card/themes/light/card.content.material.scss
- src/components/card/themes/light/card.header.material.scss
- src/components/card/themes/light/card.material.scss
> feat(card): support height for component

- src/components/dropdown/dropdown.spec.ts
- src/components/dropdown/dropdown.ts
- src/components/select/select.spec.ts
> fix(dropdown): initial update the toggle position

- src/components/combo/combo.spec.ts
- src/components/combo/combo.ts
- src/components/combo/controllers/data.ts
- src/components/combo/operations/filter.ts
- src/components/combo/operations/group.ts
- src/components/combo/types.ts
> fix(combo): primitive values not being displayed

- src/components/checkbox/themes/dark/switch.bootstrap.scss
- src/components/checkbox/themes/dark/switch.fluent.scss
- src/components/checkbox/themes/dark/switch.indigo.scss
- src/components/checkbox/themes/dark/switch.material.scss
- src/components/checkbox/themes/light/switch.base.scss
- src/components/checkbox/themes/light/switch.bootstrap.scss
- src/components/checkbox/themes/light/switch.fluent.scss
- src/components/checkbox/themes/light/switch.indigo.scss
- src/components/checkbox/themes/light/switch.material.scss
- src/styles/themes/dark/bootstrap.scss
- src/styles/themes/dark/material.scss
> refactoring(switch): consume colors from schemas

- src/components/toggle/toggle.directive.ts
`igcToggle` directive by default will try to keep the floating element anchored to its reference element on scrolling and resizing the screen.
> feat: Floating elements auto-update behavior

- src/animations/player.ts
> fix(animations): player throws warning

- src/components/combo/combo.spec.ts
- src/components/combo/controllers/selection.ts
- src/components/combo/types.ts
- stories/combo.stories.ts
> fix(combo): selection/deselection event details

- src/components/date-time-input/date-util.ts
> fix(date-time-input): use hourCycle option instead of hour12

- src/components/select/themes/light/select.bootstrap.scss
- src/components/select/themes/light/select.fluent.scss
- src/components/select/themes/light/select.indigo.scss
- src/components/select/themes/light/select.material.scss
> refactor(select): update the consumed colors

- src/components/combo/combo.spec.ts
- src/components/combo/combo.ts
- stories/combo.stories.ts
> fix(combo): single selection doesn't work as expected

- package-lock.json
- package.json
- src/components/icon/icon.base.scss
> refactor(icon): update theming and icon size

- src/components/input/themes/light/input.material.scss
> fix(input-group): floating label move inappropriately in read-only state

- src/components/input/themes/light/input.material.scss
> fix(input-group): Jumping label on focus

- src/components/button/themes/icon-button/light/icon-button.bootstrap.scss
- src/components/button/themes/icon-button/light/icon-button.fluent.scss
- src/components/button/themes/icon-button/light/icon-button.indigo.scss
- src/components/button/themes/icon-button/light/icon-button.material.scss
- stories/icon-button.stories.ts
> fix(ripple): icon button roundness

- src/components/dropdown/themes/light/item/dropdown-item.bootstrap.scss
- src/components/dropdown/themes/light/item/dropdown-item.fluent.scss
- src/components/dropdown/themes/light/item/dropdown-item.indigo.scss
- src/components/dropdown/themes/light/item/dropdown-item.material.scss
> fix(dropdown): fix active state styles

- src/components/button/themes/icon-button/dark/icon-button.fluent.scss
- src/components/button/themes/icon-button/light/icon-button.fluent.scss
> fix(icon-button): wrong color in fluent theme

- src/components/combo/combo-header.ts
- src/components/combo/combo-item.ts
- src/components/combo/themes/light/combo.bootstrap.scss
- src/components/combo/themes/light/combo.fluent.scss
- src/components/combo/themes/light/combo.indigo.scss
- src/components/combo/themes/light/combo.material.scss
- src/components/select/themes/light/select.bootstrap.scss
- src/components/select/themes/light/select.fluent.scss
- src/components/select/themes/light/select.indigo.scss
- src/components/select/themes/light/select.material.scss
> Fix dropdown in context of select and combo

- src/components/input/themes/light/input.indigo.scss
> fix(input-group): indigo theme bottom line styling

- src/components/stepper/themes/step/dark/_themes.scss
- src/components/stepper/themes/step/dark/step.bootstrap.scss
- src/components/stepper/themes/step/dark/step.fluent.scss
- src/components/stepper/themes/step/dark/step.indigo.scss
- src/components/stepper/themes/step/dark/step.material.scss
- src/components/stepper/themes/step/light/step.base.scss
- src/components/stepper/themes/step/light/step.bootstrap.scss
- src/components/stepper/themes/step/light/step.fluent.scss
- src/components/stepper/themes/step/light/step.indigo.scss
- src/components/stepper/themes/step/light/step.material.scss
- src/styles/themes/dark/bootstrap.scss
- src/styles/themes/dark/fluent.scss
- src/styles/themes/dark/indigo.scss
- src/styles/themes/dark/material.scss
> stepper: consume colors from schemas

- src/components/select/themes/light/select.material.scss
> fix(select): styling issues in outlined variant

- .eslintrc.json
- src/components/calendar/calendar-keyboard-navigation.spec.ts
- src/components/calendar/common/calendar.model.spec.ts
- src/components/icon/icon.spec.ts
- src/components/nav-drawer/nav-drawer-header-item.ts
- src/components/toggle/test.component.spec.ts
- stories/card.stories.ts
- stories/combo.stories.ts
- stories/dropdown.stories.ts
- stories/icon-button.stories.ts
- stories/icon.stories.ts
- stories/input.stories.ts
- stories/mask-input.stories.ts
- stories/nav-drawer.stories.ts
- stories/navbar.stories.ts
- stories/rating.stories.ts
- stories/select.stories.ts
Updated ESLint import plugin to be stricter with JS paths
> build: Fix ESM import paths

- src/components/checkbox/themes/light/checkbox.indigo.scss
Related to IgniteUI/igniteui-angular/issues/13444
Design handoff:
https://www.figma.com/file/PnlMVPbRLVC2MAMJbebjdh/AppBuilder---Design-System?type=design&node-id=246-15707&mode=design&t=ZchZErIEO2d0B0CT-0
> fix(checkbox): indigo theme color fixes

- src/components/calendar/themes/calendar.base.scss
> feat(calendar): fix RTL in :host parent context

- src/index.ts
> refactor(bundle): export IgcComboChangeEventArgs

- src/components/button/button-base.ts
- src/components/common/mixins/form-associated.ts
> fix: Support transpiling to ES5

- .storybook/preview.ts
- src/components/nav-drawer/nav-drawer.spec.ts
- src/components/nav-drawer/nav-drawer.ts
- src/components/nav-drawer/themes/light/nav-drawer.base.scss
- src/components/nav-drawer/themes/light/nav-drawer.bootstrap.scss
- src/components/nav-drawer/themes/light/nav-drawer.fluent.scss
- src/components/nav-drawer/themes/light/nav-drawer.indigo.scss
- src/components/nav-drawer/themes/light/nav-drawer.material.scss
- src/styles/themes/base/_theme.scss
- src/styles/utilities/_functions.scss
- src/styles/utilities/_index.scss
- stories/nav-drawer.stories.ts
> refactor(navdrawer): add transitions

- src/components/button-group/button-group.ts
could we please have something with the CI builds that checks for this in static analysis please? This keeps happening.
> emergency fix, failing the blazor builds.

- src/components/combo/combo.spec.ts
- src/components/combo/combo.ts
> fix(combo): value and selection lost on delayed data

- .storybook/preview-head.html
> storybook(preview): add titillium web font

- src/components/snackbar/themes/snackbar.base.scss
Related to IgniteUI/igniteui-angular/issues/13574
> fix(snackbar): remove unnecessary styles

- src/components/button-group/toggle-button.ts
fixes #963
doesn't fix the issue that this keeps happening though. Need to fix in the CI.
> fix build issue

- src/components/list/list-header.ts
- src/components/list/list-item.ts
- src/components/list/list.spec.ts
- src/components/list/list.ts
> fix(list): Added default intrinsic ARIA roles

- src/components/common/mixins/alert.ts
- src/components/common/utils.spec.ts
- src/components/snackbar/snackbar.spec.ts
- src/components/snackbar/snackbar.ts
- src/components/toast/toast.spec.ts
- src/components/toast/toast.ts
- stories/snackbar.stories.ts
- stories/toast.stories.ts
> refactor: Extracted a common base for snackbar and toast

- package-lock.json
- package.json
- src/components/tree/themes/shared/item.bootstrap.scss
- src/components/tree/themes/shared/item.fluent.scss
- src/components/tree/themes/shared/item.indigo.scss
- src/components/tree/themes/shared/item.material.scss
Related to https://github.com/IgniteUI/igniteui-theming/issues/125#event-10778961294
> fix(tree): consume new color from schema

- CHANGELOG.md
- src/components/button/icon-button.ts
- src/components/expansion-panel/expansion-panel.spec.ts
- src/components/icon/icon.registry.ts
- src/components/icon/icon.spec.ts
- src/components/icon/icon.ts
- src/components/icon/internal-icons-lib.ts
* Some cleanups in the registry class
* ARIA improvements for the igc-icon
Closes #985
> refactor(icon): Global registry instance

- package-lock.json
- package.json
- src/components/button-group/themes/shared/button/button.fluent.scss
> refactor(btn-group): update fluent theme styles

- src/components/combo/themes/dark/_themes.scss
- src/components/combo/themes/light/_themes.scss
- src/components/select/themes/dark/_themes.scss
- src/components/select/themes/light/_themes.scss
> fix(select/combo): wrong error color

- src/components/button/themes/button/button.base.scss
> fix(button): slotted icon size

- package-lock.json
- package.json
- src/components/navbar/themes/shared/navbar.bootstrap.scss
- src/styles/utilities/_overwrites.scss
Related to IgniteUI/igniteui-angular/issues/13868
> feat(navbar): add border in bootstrap theme

- src/components/progress/base.ts
- src/components/progress/circular-progress.spec.ts
- src/components/progress/circular-progress.ts
- src/components/progress/linear-progress.spec.ts
- src/components/progress/linear-progress.ts
* Cleaned up templates and animation logic
* Improved default ARIA
* Fixed value override on initialization before first render in the DOM
Closes #1083
> refactor: Progressbar components

- CHANGELOG.md
- src/components/date-time-input/date-time-input.spec.ts
- src/components/date-time-input/date-time-input.ts
- src/components/mask-input/mask-input-base.ts
- src/components/mask-input/mask-input.spec.ts
- src/components/mask-input/mask-input.ts
> fix(date-time-input): setRangeText updates underlying value

- src/components/snackbar/themes/shared/snackbar.indigo.scss
Related to IgniteUI/igniteui-theming/issues/193
> feat(snackbar): implement indigo design changes

- src/components/radio/themes/shared/radio.indigo.scss
Related to [this issue](https://github.com/IgniteUI/igniteui-theming/issues/180)
Here's the igniteui-theming [PR](https://github.com/IgniteUI/igniteui-theming/pull/185)
> feat(radio): update indigo radio to fit new UI kit

- CHANGELOG.md
- src/components/date-time-input/date-time-input.spec.ts
- src/components/date-time-input/date-time-input.ts
> fix(date-input): inputFormat not applied on already set value

- src/components/dialog/dialog.ts
- src/components/dialog/themes/dialog.base.scss
> fix(igc-dialog): do not display title or footer with no content

- src/components/radio/themes/shared/radio.bootstrap.scss
> fix(radio): fix radio label type style in bootstrap

- CHANGELOG.md
- src/components/common/util.ts
- src/components/dropdown/dropdown.spec.ts
- src/components/dropdown/dropdown.ts
- src/components/select/select.spec.ts
- src/components/select/select.ts
> fix(select, dropdown): Clicks inside item slotted content

- CHANGELOG.md
- src/components/tabs/tabs.spec.ts
- src/components/tabs/tabs.ts
> fix(tabs): Tabs throw if a child tab is immediately appended

- src/components/checkbox/themes/shared/switch/switch.bootstrap.scss
- src/components/list/themes/shared/item/list-item.bootstrap.scss
- src/components/nav-drawer/themes/item.ts
- src/components/nav-drawer/themes/shared/item/item.bootstrap.scss
> fix(typography): bootstrap theme type-styles

- stories/textarea.stories.ts
> fix(storybook): Default textarea story is always recreated

- src/components/banner/banner.ts
- src/components/banner/themes/banner.base.scss
- src/components/banner/themes/dark/_themes.scss
- src/components/banner/themes/dark/banner.bootstrap.scss
- src/components/banner/themes/dark/banner.fluent.scss
- src/components/banner/themes/dark/banner.indigo.scss
- src/components/banner/themes/dark/banner.material.scss
- src/components/banner/themes/light/_themes.scss
- src/components/banner/themes/light/banner.bootstrap.scss
- src/components/banner/themes/light/banner.fluent.scss
- src/components/banner/themes/light/banner.indigo.scss
- src/components/banner/themes/light/banner.material.scss
- src/components/banner/themes/shared/banner.bootstrap.scss
- src/components/banner/themes/shared/banner.fluent.scss
- src/components/banner/themes/shared/banner.indigo.scss
- src/components/banner/themes/shared/banner.material.scss
- src/components/banner/themes/themes.ts
- stories/banner.stories.ts
> Banner - add themes styling 

- biome.json
- package-lock.json
- package.json
- src/components/button-group/themes/button.ts
- src/components/button-group/themes/group.ts
- src/components/calendar/calendar-rendering.spec.ts
- src/components/common/decorators/blazorDeepImport.ts
- src/components/common/decorators/blazorIndirectRender.ts
- src/components/common/decorators/blazorSuppressComponent.ts
- src/components/common/mixins/event-emitter.ts
- src/components/common/mixins/form-associated.ts
- src/components/common/mixins/sizable.ts
- src/components/common/utils.spec.ts
- src/components/dropdown/dropdown-group.ts
- src/components/radio/utils.ts
- src/components/tree/tree.spec.ts
> build: Updated linter dependencies

- src/components/progress/base.ts
- src/components/progress/circular-progress.ts
- src/components/progress/linear-progress.ts
* Moved slotchange to a delegated handler
* Some minor template cleanups
> refactor(progressbars): Added CSS parts documentation

- src/components/combo/themes/shared/combo.common.scss
- src/components/dropdown/themes/shared/dropdown.common.scss
- src/components/popover/popover.ts
- src/components/select/themes/shared/select.common.scss
> fix(popover): white edges in dark themes

- src/components/date-picker/date-picker.spec.ts
- src/components/date-picker/date-picker.ts
- stories/divider.stories.ts
Clicks on the calendar open icon won't set the component in invalid state immediately
> fix(date-picker): Open interaction initial validation

- package-lock.json
- package.json
- src/components/calendar/themes/shared/bootstrap/year-month-view.bootstrap.scss
- src/components/calendar/themes/shared/fluent/year-month-view.fluent.scss
- src/components/calendar/themes/shared/indigo/year-month-view.indigo.scss
- src/components/calendar/themes/shared/material/year-month-view.material.scss
> build(deps): update igniteui-theming to version 9.0.0

- src/components/progress/themes/circular/circular.progress.base.scss
- src/components/progress/themes/circular/shared/circular.progress.bootstrap.scss
- src/components/progress/themes/circular/shared/circular.progress.common.scss
- src/components/progress/themes/circular/shared/circular.progress.fluent.scss
- src/components/progress/themes/circular/shared/circular.progress.indigo.scss
- src/components/progress/themes/linear/linear.progress.base.scss
- src/components/progress/themes/linear/shared/linear.progress.fluent.scss
- src/components/progress/themes/linear/shared/linear.progress.indigo.scss
Related to IgniteUI/igniteui-angular/issues/14350
> refactor(progress): update typography and sizes

- CHANGELOG.md
- src/components/stepper/animations.ts
- src/components/stepper/step.ts
- src/components/stepper/themes/step/step.base.scss
- src/components/stepper/themes/stepper/stepper.base.scss
- src/components/stepper/themes/stepper/stepper.bootstrap.scss
- stories/stepper.stories.ts
Closes [#1246](https://github.com/IgniteUI/igniteui-webcomponents/issues/1246)
> refactor(stepper): split body and content animations

- CHANGELOG.md
- src/components/date-time-input/date-time-input.spec.ts
- src/components/date-time-input/date-time-input.ts
> Date Time Input: update masked value on focus when value is set

- CHANGELOG.md
- src/components/calendar/calendar-rendering.spec.ts
- src/components/calendar/days-view/days-view.ts
> fix(calendar): Add correct dates DOM parts

- CHANGELOG.md
- package-lock.json
- package.json
- src/styles/common/component.scss
- src/styles/themes/base/_bootstrap.scss
- src/styles/themes/base/_fluent.scss
- src/styles/themes/base/_indigo.scss
- src/styles/themes/base/_material.scss
- src/styles/themes/base/_scrollbars.scss
- src/styles/themes/dark/bootstrap.scss
- src/styles/themes/dark/fluent.scss
- src/styles/themes/dark/indigo.scss
- src/styles/themes/dark/material.scss
- src/styles/themes/light/bootstrap.scss
- src/styles/themes/light/fluent.scss
- src/styles/themes/light/indigo.scss
- src/styles/themes/light/material.scss
- src/styles/utilities/_index.scss
- src/styles/utilities/_mixins.scss
Reverts IgniteUI/igniteui-webcomponents#1331
> Revert "refactor(scrollbar): Update the styles to consume colors from schemas"

- src/components/common/controllers/gestures.spec.ts
- src/components/common/controllers/gestures.ts
- src/components/common/utils.spec.ts
This commit adds very basic support for swipe
gestures only.
> feat: Added basic gestures controller

- src/components/nav-drawer/themes/container.base.scss
> refactor(navdrawer): use min-width in the mini variant

- src/components/icon/icon-references.ts
- stories/date-time-input.stories.ts
> refactor(icon-rigistry): update input expand/collapse icons

- src/components/chip/themes/shared/chip.common.scss
> feat(chip): update slotted items size

- src/components/expansion-panel/themes/expansion-panel.base.scss
- src/components/expansion-panel/themes/shared/expansion-panel.bootstrap.scss
- src/components/expansion-panel/themes/shared/expansion-panel.common.scss
- src/components/expansion-panel/themes/shared/expansion-panel.fluent.scss
> fix(expansion-panel): text styles and typography

- src/components/icon/icon-state.broadcast.ts
In order to be consistent wth the [bfcache](https://web.dev/articles/bfcache) of the
browser, dispose of the icon service broadcast channel when the page is "unloading".
> fix(icon-service): Dispose of broadcast channel on pagehide

- src/components/checkbox/checkbox-base.ts
- src/components/checkbox/checkbox.spec.ts
- src/components/checkbox/checkbox.ts
> fix(switch, checkbox): click event fires more than once

- src/components/tile-manager/controllers/fullscreen.ts
- src/components/tile-manager/tile-manager.ts
- src/components/tile-manager/tile.ts
This is a PoC but we can evaluate if this is something we want and design UX around it.
> feat(tile-manager): Added fullscreen behavior for tiles

- CHANGELOG.md
- src/components/calendar/calendar.interaction.spec.ts
- src/components/calendar/days-view/days-view.ts
- src/components/calendar/months-view/months-view.ts
- src/components/calendar/years-view/years-view.ts
> fix(calendar): Cannot select dates before UNIX epoch

- src/components/card/themes/card.actions.base.scss
> fix(card): fix card actions content alignment in vertical orientation.

- src/components/dialog/themes/shared/dialog.fluent.scss
> fix(dialog): fluent theme typography

- src/components/dropdown/themes/header.ts
- src/components/dropdown/themes/shared/dropdown.bootstrap.scss
- src/components/dropdown/themes/shared/header/dropdown-header.fluent.scss
- update fluent headers to subtitle-2
closes #1462
> fix(dropdown): remove bootstrap top and bottom padding from the base part

- src/components/list/themes/item.base.scss
- src/components/list/themes/shared/container/list.indigo.scss
- src/components/list/themes/shared/item/list-item.common.scss
- src/components/list/themes/shared/item/list-item.indigo.scss
> refactor(list): update item gaps

- src/components/radio/radio.ts
> fix(radio): remove label part when there's no text in the slot

- src/components/checkbox/checkbox-base.ts
- src/components/checkbox/checkbox.ts
- src/components/checkbox/themes/checkbox.base.scss
- src/components/checkbox/themes/shared/checkbox/checkbox.bootstrap.scss
- src/components/checkbox/themes/shared/checkbox/checkbox.fluent.scss
- src/components/checkbox/themes/shared/checkbox/checkbox.indigo.scss
- src/components/checkbox/themes/shared/checkbox/checkbox.material.scss
Closes https://github.com/IgniteUI/igniteui-webcomponents/issues/1478
> fix(checkbox): remove extra gap

- src/components/avatar/themes/shared/avatar.common.scss
- src/components/avatar/themes/shared/avatar.indigo.scss
- stories/avatar.stories.ts
> fix(avatar): slotted icon size

- stories/stepper.stories.ts
> fix(stepper): linear property in story not working

- package-lock.json
- package.json
Removed git add from lint-staged since it is
deprecated since v10.
> build(deps): Bumped dependencies

- src/components/textarea/themes/shared/textarea.common.scss
> fix(textarea): helper text disabled color

- src/components/input/themes/shared/input.common.scss
- src/components/input/themes/shared/input.indigo.scss
> fix(input): invalid helper text

- src/components/combo/combo.spec.ts
- src/components/combo/combo.ts
> fix(combo): default value with delayed data

- src/components/button/themes/icon-button/shared/icon-button.material.scss
> fix(icon-button): material outlined button not visible

- src/components/navbar/themes/navbar.base.scss
- src/components/navbar/themes/shared/navbar.indigo.scss
Related to IgniteUI/igniteui-angular/pull/15345
> fix(navbar): slotted components sizes

- biome.json
- scripts/build-stories.mjs
- scripts/build-typedoc.js
- src/components/icon/icon.spec.ts
- stories/dialog.stories.ts
- stories/textarea.stories.ts
- stories/tree.stories.ts
Force to error out on unused variables, import statements, function arguments and private class members.
Updated TypeDoc build script.
> style(lint): Updated Biome rules to a more strict subset

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
Reverted keep-a-changelog version
> docs: Updated CHANGELOG

- src/components/checkbox/themes/shared/switch/switch.bootstrap.scss
- src/components/checkbox/themes/shared/switch/switch.common.scss
- src/components/checkbox/themes/shared/switch/switch.fluent.scss
- src/components/checkbox/themes/shared/switch/switch.indigo.scss
- src/components/checkbox/themes/shared/switch/switch.material.scss
Related to IgniteUI/igniteui-theming/issues/382
> refactor(switch): remove invalid state props

- src/components/chip/themes/shared/chip.bootstrap.scss
> fix(chip): update bootstrap chip styles

- src/components/stepper/themes/step/step.base.scss
> fix(stepper) fix header text aligment

- package-lock.json
- package.json
- vite.config.ts
* Migrated vite.config to use the new scss API config
> build(deps): Bumped typescript version

- package-lock.json
- package.json
- src/components/rating/themes/rating.base.scss
- src/components/rating/themes/shared/rating.common.scss
- src/components/rating/themes/shared/rating.indigo.scss
Related to IgniteUI/igniteui-webcomponents#1655
> fix(rating): overwritten properties

- src/components/combo/themes/combo.base.scss
> fix(combo): use hardcoded color for case-icon in all themes

- src/components/common/controllers/key-bindings.ts
- src/components/common/util.ts
- src/components/date-time-input/date-time-input.ts
- src/components/dropdown/dropdown.ts
- src/components/radio/radio.ts
* Fixed an issue where *handleEvent* would trigger for unrelated key/modifier combinations and removed workarounds from associated components.
* Restructured the code and added better type information.
* Some minor performance improvements.
> refactor: Keybinding controller

- src/components/input/themes/shared/input.indigo.scss
- src/components/textarea/themes/shared/textarea.bootstrap.scss
- src/components/textarea/themes/shared/textarea.common.scss
- src/components/textarea/themes/shared/textarea.fluent.scss
- src/components/textarea/themes/shared/textarea.indigo.scss
- src/components/textarea/themes/shared/textarea.material.scss
- stories/textarea.stories.ts
> feat(textarea): readonly styles

- src/components/card/themes/content.ts
- src/components/card/themes/shared/content/card.content.indigo.scss
Related to IgniteUI/igniteui-react/issues/102
> fix(card): indigo theme avatar size

- src/components/input/themes/shared/input.material.scss
> fix(input): adjust placeholder-shown styles and label alignment in material theme

- src/components/textarea/themes/shared/textarea.material.scss
> fix(textarea): fix resize issue and make textarea editable

- package-lock.json
- package.json
- src/styles/themes/base/_theme.scss
Depends on https://github.com/IgniteUI/igniteui-theming/pull/458
> refactor(themes): consume spacing from theming package

- src/components/combo/themes/shared/combo.indigo.scss
- src/components/select/themes/shared/select.indigo.scss
> feat(select/combo): fix icon sizes for indigo
