- src/components/checkbox/checkbox-base.ts
- src/components/common/decorators/blazorTwoWayBind.ts
- src/components/common/decorators/index.ts
- src/components/input/input.ts
- src/components/radio/radio.ts
at the blazor level
This includes a new decorator and applies it in a few places. This has no runtime implications but serves as a hint for how to arrange the blazor wrapper in order to support bidirectional binding for the annotated property.
> add attributes to configure bidirational binding

- src/components/button/button.material.scss
The flat button with material theme gains background when disabled:
As far as I can tell from the [material design reference](https://material.io/components/buttons#text-button) is should still have no background and tht puts it in line w/ Ignite UI for Angular's button:
> fix(themes,button): flat button background in material

- src/components/button/button.bootstrap.scss
- src/styles/themes/bootstrap.scss
Closes: #105 #99
1. Update the bootstrap palette colors too much the bootstrap v5.1.3  palette. 
2. Fix the button styles to match as much as possible the bootstrap v5.1.3  buttons.
> refactor(button): improve button sizing and palette

- src/components/avatar/avatar.ts
> fix: Setting avatar src correctly resets error state

- package.json
Generate a keep a changelog release notes.
Run the command with
`npm run release -- --release [version]`
> docs: Expose changelog command through npm scripts

- src/components/avatar/avatar.spec.ts
- src/components/badge/badge.spec.ts
- src/components/button/button-base.ts
- src/components/button/button.spec.ts
- src/components/button/icon-button.spec.ts
- src/components/calendar/calendar-keyboard-navigation.spec.ts
- src/components/calendar/calendar-rendering.spec.ts
- src/components/calendar/calendar.ts
- src/components/card/card.spec.ts
- src/components/checkbox/checkbox.spec.ts
- src/components/checkbox/switch.spec.ts
- src/components/form/form.spec.ts
- src/components/icon/icon.spec.ts
- src/components/list/list.spec.ts
- src/components/nav-drawer/nav-drawer.spec.ts
- src/components/navbar/navbar.spec.ts
- src/components/radio-group/radio-group.spec.ts
- src/components/radio/radio.spec.ts
- stories/button.stories.ts
- stories/icon-button.stories.ts
It appears that if we don't have `await` ([docs](https://open-wc.org/docs/testing/testing-package/#chai)) on the `accessible()` expect, it fails silently. I have added `await` and fixed all accessibility issues that came up.
> feat(a11y): fix a11y tests

- src/components/expansion-panel/themes/light/expansion-panel.base.scss
- src/components/expansion-panel/themes/light/expansion-panel.bootstrap.scss
- src/components/expansion-panel/themes/light/expansion-panel.fluent.scss
- src/components/expansion-panel/themes/light/expansion-panel.indigo.scss
- stories/expansion-panel.stories.ts
- stories/input.stories.ts
The expansion panel, as it was, was not working with heading elements when passed to the slots for title, subtitle, etc. Additional improvements are introduced in this PR.
> fix(expansion-panel): not working with headings

- src/components/nav-drawer/nav-drawer-header-item.ts
- src/components/nav-drawer/nav-drawer-item.ts
- src/components/nav-drawer/nav-drawer.ts
- src/components/nav-drawer/styles/fluent/nav-drawer-header-item.fluent.scss
- src/components/nav-drawer/styles/fluent/nav-drawer-item.fluent.scss
- src/components/nav-drawer/styles/indigo/nav-drawer-header-item.indigo.scss
- src/components/nav-drawer/styles/indigo/nav-drawer.indigo.scss
- src/components/nav-drawer/themes/dark/nav-drawer-item.base.scss
- src/components/nav-drawer/themes/dark/nav-drawer-item.bootstrap.scss
- src/components/nav-drawer/themes/dark/nav-drawer-item.fluent.scss
- src/components/nav-drawer/themes/dark/nav-drawer-item.indigo.scss
- src/components/nav-drawer/themes/dark/nav-drawer.indigo.scss
- src/components/nav-drawer/themes/light/fluent/nav-drawer-header-item.fluent.scss
- src/components/nav-drawer/themes/light/fluent/nav-drawer-item.fluent.scss
- src/components/nav-drawer/themes/light/indigo/nav-drawer-header-item.indigo.scss
- src/components/nav-drawer/themes/light/indigo/nav-drawer-item.indigo.scss
- src/components/nav-drawer/themes/light/indigo/nav-drawer.indigo.scss
- src/components/nav-drawer/themes/light/nav-drawer-header-item.base.scss
- src/components/nav-drawer/themes/light/nav-drawer-item.base.scss
- src/components/nav-drawer/themes/light/nav-drawer.base.scss
- src/styles/themes/dark/bootstrap.scss
- src/styles/themes/dark/fluent.scss
- src/styles/themes/dark/indigo.scss
- src/styles/themes/dark/material.scss
> fix(nav-drawer): different colors in WC and Angular

- src/components/rating/rating-symbol.base.scss
- src/components/rating/rating.ts
Step would be set to 1 on initial render regardless of the provided step value. Also, the current value should be ceiled when switching to single selection mode to avoid a visual glitch where the selected symbol will not show if the value is a floating number.
This PR also fixes a rendering issue in Firefox when emojis are used due to line-height being set explicitly.
> fix(rating): step and line-height

- src/components/tabs/themes/light/tab.base.scss
Misalignment when icon and text are displayed horizontally
> fix(tabs): icon & text misalignment

- src/components/common/util.ts
- src/components/radio-group/radio-group.ts
- src/components/rating/rating.ts
- src/components/slider/slider-base.ts
- src/components/tabs/tabs.ts
- Extracted `isLTR` to an external helper function.
- Reduced number of LTR query calls in certain scenarios to avoid
reflow thrashing.
- Cached rating symbols rendering logic. Properties not related
to the symbols state will not trigger a DOM re-render.
> refactor: Reduced LTR query calls and improved rating rendering

- CHANGELOG.md
- src/components/chip/chip.ts
- src/components/icon/icon.ts
- stories/chip.stories.ts
- stories/icon.stories.ts
> feat(*): role property to icon, focusable remove chip

- CHANGELOG.md
- src/components/toast/toast.spec.ts
- src/components/toast/toast.ts
- stories/toast.stories.ts
> fix(toast): adding alert role for toast

- CHANGELOG.md
- src/components/calendar/days-view/days-view.ts
> fix(calendar): Range selection a11y improvement

- src/components/rating/rating-symbol.ts
- src/components/rating/rating.spec.ts
- src/components/rating/rating.ts
The default rendering of the Rating (when no custom symbols are provided) is handled by the default slot fallback content. However, many frameworks (read: Angular, Blazor, even Lit) like to leave anchor nodes for possible content, usually comments like this:
```html
<igc-rating size="large">  </igc-rating>
```
This triggers the default slot projection and wipes the fallback content leaving an empty rating.
To avoid this, moved to a named slot with a self-assign approach for the rating symbol components, similar to the Tab panels.
> fix(rating): only projected symbols override default content

- src/components/checkbox/checkbox-base.ts
- src/components/checkbox/checkbox.ts
- src/components/checkbox/switch.ts
- src/components/checkbox/themes/light/checkbox.base.scss
- src/components/checkbox/themes/light/switch.base.scss
- src/components/radio/radio.ts
- src/components/radio/themes/light/radio.base.scss
> fix(checkbox/radio/switch): extra margin without label

- src/components/checkbox/checkbox-base.ts
- src/components/radio/radio.ts
- src/components/select/select-group.ts
- src/components/slider/slider-base.ts
Several components did not call the parent `disconnectedCallback`, preventing triggering `hostDisconnected`
for any controllers (theming in this case) and
leading to a memory leak.
> fix: Dangling references after element disconnect

- src/animations/easings.ts
- src/animations/index.ts
- src/animations/player.spec.ts
- src/animations/player.ts
- src/animations/presets/grow/index.ts
- src/animations/presets/index.ts
- src/animations/types.ts
- src/components/accordion/accordion.ts
- src/components/accordion/themes/accordion.base.scss
- src/components/expansion-panel/expansion-panel.spec.ts
- src/components/expansion-panel/expansion-panel.ts
- src/components/expansion-panel/themes/light/expansion-panel.base.scss
- stories/accordion.stories.ts
- stories/expansion-panel.stories.ts
Closes #599 
Add a basic animation player that plays Web Animations and calls a function when the animation finishes playing. As a bonus feature, the animation player will animate height automatically if its value is set to 'auto'.
This PR animates the expansion panel as a showcase for how the player can be used.
> feat(animations): add a basic animation player

- package-lock.json
- package.json
Once internal glob support is brough back for non-POSIX envs this repository will migrate to v4.
Closes #647
> build: Downgraded rimraf to v3

- src/components/combo/combo-header.ts
- src/components/combo/combo-item.ts
- src/components/combo/combo-list.ts
- src/components/combo/combo.ts
combo-header, combo-item and combo-list are not publically [exposed](https://github.com/IgniteUI/igniteui-webcomponents/blob/master/src/index.ts) so I am suppressing them for blazor.
> suppress internal combo components for blazor

- src/components/mask-input/mask-input.ts
This is to prevent C# from generating a shadowed version of this method when it is not necessary.
> blazor suppress setRangeText on mask input

- src/components/toggle/toggle.directive.ts
Refactor the size middleware apply callback syntax:
While it was perfectly valid, it apparently can be confusing to some bundlers (perhaps too ambiguous with a func call) or the inline parameter destructive assign.. either way, at least in one case it made for a completely invalid argument handling that throws, so hopefully this is a little clearer. Certainly easier to read IMHO.
> refactor(toggle): change middleware apply destructing assign

- src/components/combo/combo.ts
These can be handled by static analysis and resolved to baseline object array and string properties
> chore(combo): drop blazorAlternateType meta that's now redundant

- src/components/combo/combo.ts
- src/components/select/select.ts
Fixes https://github.com/IgniteUI/igniteui-angular/issues/13096
Issue is specific to Chromium-based browsers and doesn't reproduce in Firefox and the Select/Combo being used as templates in the Elements Grid, so no cleaner repro available.
It's to do with how blur is handled immediately before an element is discarded from the DOM, which is exactly what the Grid's virtualization does - blurs the `activeElement` (to avoid a previous bug with that being removed from the DOM) on scroll and then if scrolled further enough the select/combo template might also be replaced with different content, i.e. removed from the DOM.
It's not a 100% consistent, but when that happens in quick succession you get a cryptic error for `insertBefore` with completely unrelated stack.
Tracking this down, narrowing …
> fix(select,combo): error in Chromium on remove from DOM after blur

- src/components/dropdown/dropdown.ts
- src/components/expansion-panel/expansion-panel.ts
- src/components/select/select.ts
- src/components/snackbar/snackbar.ts
- src/components/toast/toast.ts
Couple of newly added and some more missed from before `firstUpdated` overrides as public that show up in API docs - marked protected.
> Keep firstUpdated overrides protected

- src/components/combo/combo.spec.ts
- src/components/combo/combo.ts
Assign a default `any` to the Combo's generic type param so the type can be used without necessarily specifying it (can also default to object I suppose?).
Also explicitly typing `selection` - so far it's inferred correctly, but just in case the code changes.
> refactor(combo): generic type param default, explicit selection type

- src/components/stepper/step.ts
Don't think this prop on the step was meant to be public (not in the spec for sure), so marking it as internal. Feel free to correct me if not the case.
> docs(stepper): drop internal prop from public API

- src/components/combo/combo.ts
- src/components/select/select.ts
- stories/combo.stories.ts
- stories/select.stories.ts
Hide deprecated properties from elements manifest and API documentation
> chore: igc-select flip on by default

- .storybook/preview.ts
closes #822 
This fixes the icon color in the dark themes since the icon default color is set to 'currentColor'
> feat(stories): Adding global color to all previews

- src/components/dropdown/dropdown-header.ts
Ensure full extension for the css import as in some consuming apps (namely Webpack depending on config) it will fail to build with "Module not found: Error: Can't resolve './themes/light/header/dropdown-header.base.css'"
> fix(dropdown): header css import extension

- src/components/stepper/themes/step/light/step.base.scss
- src/components/stepper/themes/step/light/step.bootstrap.scss
- src/components/stepper/themes/step/light/step.fluent.scss
- src/components/stepper/themes/step/light/step.indigo.scss
- src/components/stepper/themes/step/light/step.material.scss
closes #766
This makes the styles persistent even when the indicator is slotted.
> refactor(stepper): add color state styles directly to the indicator part

- src/animations/presets/fade/index.ts
- src/animations/presets/grow/index.ts
- src/animations/presets/index.ts
- src/animations/presets/slide/index.ts
- src/components/dialog/dialog.ts
- src/components/expansion-panel/expansion-panel.ts
- src/components/snackbar/snackbar.ts
- src/components/stepper/animations.ts
- src/components/stepper/step.ts
- src/components/stepper/stepper.ts
- src/components/stepper/themes/step/light/step.base.scss
- src/components/stepper/themes/stepper/stepper.base.scss
- src/components/toast/toast.ts
- src/components/tree/tree-item.ts
- stories/stepper.stories.ts
> feat(stepper): add animations

- CHANGELOG.md
- src/components/combo/combo.spec.ts
- src/components/combo/combo.ts
- src/components/combo/controllers/data.ts
- src/components/combo/operations/group.ts
- src/components/combo/types.ts
> feat(Combo): Add support for groupingDirection: none .Remove the sorting of the items when combo has grouping.

- CHANGELOG.md
- src/components/tree/tree-item.ts
> fix(tree): Active tree item on click

- src/components/slider/themes/slider.base.scss
Fix taken from https://github.com/IgniteUI/igniteui-angular/pull/14052
Test against https://igniteui.github.io/igniteui-webcomponents/?path=/docs/slider--docs with dev tools emulation or on mobile and the pointer handling doesn't work for sliding without this.
> fix(slider): allow touch sliding

- CHANGELOG.md
- src/components/button-group/button-group.spec.ts
- src/components/button-group/button-group.ts
> feat(button-group): clear selection via selectedItems

- .storybook/main.ts
The autodocs feature is of questionable value in our current build as it creates "invalid" states of how a component behaves (see #1171 as a recent example). Dumping all the samples and a table of properties without any additional explanation and guidance is not enough IMO. We already have dedicated pages for samples and documentation topics.
Let's disable the autodocs. If we want to improve the Storybook samples with additional documentation and user stories, then we should create a task for it.
> build: Disabled storybook autodocs feature

- CHANGELOG.md
- src/components/combo/combo.ts
- src/components/dropdown/dropdown.ts
- src/components/popover/popover.spec.ts
- src/components/popover/popover.ts
- src/components/popover/themes/light/popover.base.scss
- src/components/select/select.ts
- stories/combo.stories.ts
- stories/dialog.stories.ts
- stories/dropdown.stories.ts
Now that the dropdown container is rendered in the browser's top layer, the `positionStrategy` property, previously used to avoid clipping by an ancestor, has become obsolete.
> deprecate(dropdown): positionStrategy deprecation

- src/components/button-group/button-group.ts
Use `findElementFromEventPath` in the click handler
> refactor(btn-group): Removed theme property listener

- src/components/mask-input/mask-parser.ts
* Removed extra calls to `parseMaskLiterals` around the codebase.
* Improved `apply` memory allocations by modifying an array instead of re-creating the masked string
for each character.
> refactor(mask): Parser perf improvements

- CHANGELOG.md
- src/components/date-time-input/date-time-input.ts
- tsconfig.json
* Additionally cleaned up some low-hanging code for easier reading.
Closes #1166
> fix(date-time input): Label in Material with read-only

- src/components/button-group/toggle-button.ts
- src/components/common/util.ts
- src/components/common/validators.ts
- src/components/date-time-input/date-time-input.ts
- src/components/progress/base.ts
- src/components/rating/rating.ts
- src/components/slider/slider-base.ts
- src/components/stepper/step.ts
- src/components/tabs/tab.ts
- src/components/tabs/tabs.ts
- src/components/tree/tree-item.ts
* Skip the creating of a dynamic theme property when initializing a web component class instance
for components which don't need it.
* Minor cleanups in utils and rating hover event handlers.
> refactor: Do not create dynamic theme property

- src/components/dropdown/dropdown.ts
Sadly, I don't think there's a good way for this to be folded into 4.9.x to have a consistent base for the analyzer ¯\_(ツ)_/¯
> docs(dropdown): deprecation format

- package-lock.json
- package.json
- src/components/common/util.ts
- src/components/input/input.spec.ts
Changed `isLTR` to use the new `:dir(ltr|rtl)` selector, instead of the `getComputedStyle` call which triggers a style reflow. After some prelimenary benchmarks it seems to be ~80% faster for repeated calls.
This is already baseline for our target browsers but I had to updated the playwright package version so it can support the new syntax.
As an added bonus since the new version supports `URL.canParse` I've added a test for the input as well.
> perf(core): Improved LTR-RTL detection

- CHANGELOG.md
- src/components/radio-group/radio-group.spec.ts
- src/components/radio-group/radio-group.ts
- src/components/radio/radio.ts
- src/components/radio/utils.ts
- stories/radio-group.stories.ts
Added `name` and `value` properties on the igc-radio-group. Developers can now control the checked state of the underlying igc-radio components through the enclosing group.
Closes #315
> feat(radio-group): Set radio properties through the group

- CHANGELOG.md
- src/components/nav-drawer/nav-drawer.spec.ts
- src/components/nav-drawer/nav-drawer.ts
> fix(nav-drawer): Mini variant not initially visible

- src/components/calendar/calendar.ts
- src/components/combo/combo.ts
- src/components/date-picker/date-picker.ts
- src/components/icon/icon-references.ts
- src/components/icon/icon.registry.ts
- src/components/icon/icon.ts
- src/components/icon/internal-icons-lib.ts
- src/components/icon/registry/default-map.ts
- src/components/icon/registry/parser.ts
- src/components/icon/registry/types.ts
- src/components/input/input-base.ts
- src/components/select/select.ts
- src/components/textarea/textarea.ts
- src/index.ts
- src/theming/config.spec.ts
- src/theming/config.ts
- src/theming/theming-controller.ts
- src/theming/theming-decorator.ts
- src/theming/theming-event.ts
- src/theming/types.ts
- src/theming/utils.ts
* Refactored some of the logic inside the icon registry around the default internal collection of icons.
* Revamped the themes decorator to be more explicit when the controller is exposed to the decorated element.
* Changed the typing around the decorator.
* Refactored the logic around getting the shared/theme styles.
* Exposed a new property on the theming decorator, `onThemeChanged`. Elements can register a callback accepting the new theme and run some logic before the element is re-rendered.
> refactor: Icon registry and theming stack

- CHANGELOG.md
- src/components/radio/radio.spec.ts
- src/components/radio/radio.ts
> refactor(radio): Changed the igcChange custom event type

- src/components/checkbox/checkbox-base.ts
- src/components/common/controllers/key-bindings.ts
- src/components/common/controllers/mutation-observer.ts
- src/components/divider/divider.ts
- src/components/icon/registry/types.ts
- src/components/radio-group/radio-group.ts
- src/components/radio/radio.ts
- refactor: fix radio & checkboxes two-way meta adjust for evt detail changes from #1302 & #1303
- refactor(radio-group): add two-way meta tag for value related to #1262 & #315
- Divider prop adjust and some cleanup
> refactor: analyzer meta adjustments

- CHANGELOG.md
- src/components/select/select.spec.ts
- src/components/select/select.ts
Pressing Tab in a select with open dropdown when
the active item matches the current selection now
correctly moves the focus back on the select after closing the dropdown.
> fix(select): Tab key behaviour with open dropdown

- src/components/dropdown/themes/dropdown-item.base.scss
- src/components/dropdown/themes/header.ts
- src/components/dropdown/themes/shared/dropdown.common.scss
- src/components/dropdown/themes/shared/dropdown.fluent.scss
- src/components/dropdown/themes/shared/dropdown.indigo.scss
- src/components/dropdown/themes/shared/dropdown.material.scss
- src/components/dropdown/themes/shared/header/dropdown-header.common.scss
- src/components/dropdown/themes/shared/header/dropdown-header.fluent.scss
- src/components/dropdown/themes/shared/header/dropdown-header.indigo.scss
- src/components/dropdown/themes/shared/item/dropdown-item.common.scss
- src/components/dropdown/themes/shared/item/dropdown-item.fluent.scss
- src/components/dropdown/themes/shared/item/dropdown-item.indigo.scss
- stories/dropdown.stories.ts
Closes #1405 
Closes #1407 
Inspect the combo along with the dropdown.
> refactor(dropdown): update items sizes and paddings

- package.json
Point the internal package.json to the src directory so Storybook and Vite can serve the latest version of the files while developing.
> chore(storybook): Sourcemaps and files for SB cache

- src/theming/theming-controller.ts
- src/theming/theming-event.ts
Dropped the set collection of registered callbacks for components. Instead add the callback directly
as an event listener to the global theme emitter.
> refactor: Use an EventTarget derived emitter for theme changes

- src/components/chip/themes/chip.base.scss
Closes: #1583
Replaces flex with grid to mathc angular implementation and to make ellipsis work. Simplifies margin logic by using `gap` and removes redundant parts' styles. Adds `ellipsis()` to truncate text and sets a max width for slotted content to match angular behavior.
> fix(chip) styles for improved layout and responsiveness.

- CHANGELOG.md
- src/components/list/list-item.ts
- src/components/list/themes/shared/item/list-item.common.scss
- stories/avatar.stories.ts
> feat(list-item): add selected property

- .github/CONTRIBUTING.md
- .github/workflows/node.js.yml
- .github/workflows/npm-publish.yml
- scripts/build.mjs
> build: Bump build scripts and CI to a more recent Node LTS version

- src/components/calendar/themes/shared/material/days-view.material.scss
> [calendar] - Fix date text color in range selection when the current date is also the last or first in range

- CHANGELOG.md
- src/components/checkbox/checkbox-base.ts
- src/components/common/util.ts
- src/components/dropdown/dropdown.ts
- src/components/popover/popover.ts
- src/components/radio/radio.ts
- src/components/select/select.ts
- src/components/slider/range-slider.ts
- src/components/stepper/stepper.common.ts
- src/components/tree/tree-navigation.spec.ts
- src/components/tree/tree-selection.spec.ts
- src/components/tree/tree.common.ts
- src/components/tree/tree.selection.ts
- src/index.ts
- Exposed `IgcCalendarResourceStrings`,  renamed and exposed `PopoverPlacement` (Dropdown and Select) and `IgcTreeSelectionEventArgs` (after small internal refactor) from the public API
- Made all event args consistenly `Igc-` prefixed and `-EventArgs` suffixed. Existing types are aliased and kept as deprecated for this release.
> Missing API exports, unify event args naming

- src/components/popover/popover.ts
- src/components/popover/themes/light/popover.base.scss
This fix minimizes the amount of jitter when an
open popover tries to reposition against its
target while scrolling or resizing.
**Before - Fixed position**:
https://github.com/user-attachments/assets/a00159b2-fa7d-48ac-87c5-351d6020d76b
**After - Absolute position**
https://github.com/user-attachments/assets/416a4801-969e-45e2-b86f-44ece79c2720
> fix(popover): Use absolute position and strategy

- .gitignore
This PR adds some common files and folders to .gitignore used when creating local development environments, useful for testing the package with different Node.js versions without relying on nvm or similar packages.
> chore: add .envrc and .direnv to .gitignore

- CHANGELOG.md
- src/components/date-time-input/date-time-input.spec.ts
- src/components/date-time-input/date-time-input.ts
> fix(date-time-input): ensure 'igcChange' is emitted in case an incomplete mask value has been filled

- src/components/tabs/tab-dom.ts
- src/components/tabs/tabs.spec.ts
Check for the existence of the tab header strip and indicator, if applicable, before trying to manipulate DOM state inside the observers callbacks.
> fix(tabs): Internal DOM reference checks in observers

- CHANGELOG.md
- src/components/tooltip/tooltip.spec.ts
- src/components/tooltip/tooltip.ts
docs: Updated CHANGELOG with release notes.
> refactor(tooltip): Align API and behavior to Angular tooltip

- src/components/calendar/calendar.ts
- src/components/calendar/days-view/days-view.ts
- src/components/calendar/months-view/months-view.ts
- src/components/calendar/years-view/years-view.ts
- src/components/date-range-picker/date-range-picker.ts
This PR prevents the focus scroll after opening the dropdown of a date range picker, causing a viewport shift which leads to deteriorated UX.
It will also set the active days view index to always be the first one, improving UX after selection is made.
> fix(date-range-picker): Consistent focus on open and active day view

- src/components/button-group/button-group.ts
- src/components/carousel/carousel.ts
- src/components/common/controllers/mutation-observer.ts
- src/components/select/select-group.ts
- src/components/tabs/tabs.ts
* Added the feature to get the changed attribute name inside the observer callback.
* Restructured some code in the controller implementation.
* Improved types and documentation.
* Fixed call-site usage with the new API.
> refactor: Mutation observer controller

- CHANGELOG.md
- src/components/carousel/carousel.spec.ts
- src/components/carousel/carousel.ts
> fix(carousel): pause auto-rotation on pointer focus

- CHANGELOG.md
- src/components/carousel/carousel.spec.ts
- src/components/carousel/carousel.ts
> fix(carousel): emit igcSlideChanged on slide change

- src/components/calendar/calendar-rendering.spec.ts
- src/components/calendar/calendar.ts
- src/components/calendar/helpers.spec.ts
- src/components/calendar/themes/calendar.base.scss
- src/components/calendar/themes/shared/bootstrap/calendar.bootstrap.scss
- src/components/calendar/themes/shared/fluent/calendar.fluent.scss
- src/components/calendar/themes/shared/indigo/calendar.indigo.scss
- src/components/calendar/themes/shared/material/calendar.material.scss
> fix(calendar): reflect the orientation attr.

- src/components/date-range-picker/date-range-picker-single.spec.ts
- src/components/date-range-picker/date-range-picker-two-inputs.spec.ts
- src/components/date-range-picker/date-range-picker.ts
> fix(date-range-picker): focus on arrow-up/escape for single input

- src/components/card/themes/card.content.base.scss
- src/components/card/themes/card.header.base.scss
This PR fixes the behavior of sizing the avatar in the context of the Card component for all themes, except Indigo, where it's already being sized correctly.
> fix(card): default avatar size not correct in all themes bar indigo

- src/components/list/themes/dark/header/list-header.bootstrap.scss
- src/components/list/themes/dark/header/list-header.fluent.scss
- src/components/list/themes/dark/header/list-header.indigo.scss
- src/components/list/themes/dark/header/list-header.material.scss
- src/components/list/themes/dark/item/list-item.bootstrap.scss
- src/components/list/themes/dark/item/list-item.fluent.scss
- src/components/list/themes/dark/item/list-item.indigo.scss
- src/components/list/themes/dark/item/list-item.material.scss
- src/components/list/themes/header.ts
- src/components/list/themes/item.ts
- src/components/list/themes/light/header/list-header.bootstrap.scss
- src/components/list/themes/light/header/list-header.fluent.scss
- src/components/list/themes/light/header/list-header.indigo.scss
- src/components/list/themes/light/header/list-header.material.scss
- src/components/list/themes/light/item/list-item.bootstrap.scss
- src/components/list/themes/light/item/list-item.fluent.scss
- src/components/list/themes/light/item/list-item.indigo.scss
- src/components/list/themes/light/item/list-item.material.scss
This PR fixes a critical issue with the list component that prevents it from being styled using CSS variables alone.
The component includes the CSS variables for the list theme in all list-related components (list-item, list-header, and the list host itself), forcing people to have to override the variables in all three instances.
This PR includes the theme CSS variables only in the list host, while component specific overrides for the item and header are preserved and carried by each component separately.
> fix(list): theme variables replicated for all list components
